Repository guacsec/trustify-ui, pull requests merged in 2025-02, with the labels that each got.

#341 ci: add backport action
  .github/workflows/backport.yaml
Labels: backport release/0.2.z

#331 Avoid saving files generated by trustd.yaml | "openapi spec" into git
  .github/workflows/ci-global.yaml
  .gitignore
  client/package.json
  client/src/app/client/index.ts
  client/src/app/client/schemas.gen.ts
  client/src/app/client/services.gen.ts
  client/src/app/client/types.gen.ts
  package.json
Labels: ci, backport release/0.2.z

#344 fix: Search Page does not search on the backend while typing
  client/src/app/pages/search/components/SearchMenu.tsx
  client/src/app/pages/search/components/SearchTabs.tsx
  client/src/app/pages/search/components/filterEntityListByValue.test.ts
  client/src/app/pages/search/search.tsx
  client/src/app/queries/advisories.ts
  client/src/app/queries/packages.ts
  client/src/app/queries/sboms.ts
  client/src/app/queries/vulnerabilities.ts
Labels: backport release/0.2.z

#362 :sparkles: update client/openapi/trustd.yaml
  client/openapi/trustd.yaml
Labels: cherry-pick/release/0.2.z

#379 :sparkles: sbom details page - filter out duplicate packages
  client/src/app/pages/sbom-details/vulnerabilities-by-sbom.tsx
Labels: cherry-pick/release/0.2.z

#361 :sparkles: add importer filters
  client/src/app/pages/importer-list/importer-list.tsx
Labels: cherry-pick/release/0.2.z
